### ISSUE TITLE
"Read as Binary File"can't work

### ISSUE THREAD

**Issue by yaomq19** [marwankau/BinaryFileViewer#24]
![image](https://github.com/marwankau/BinaryFileViewer/assets/90727335/491a09b8-85c2-46f2-99be-4f504a012c8d)
Hello!Thanks for contributions!But "Read as Binary File"can't work.

**Comment by marwankau** [comment]
Thank you for asking.

I update the code and add (Read as Binary File) implementation.

It was assignment for my students last year to be completed by them.
